# Auto-label PRs based on file paths
# Requires: actions/labeler@v5

cli:
  - changed-files:
      - any-glob-to-any-file:
          - "src/cli/**"
          - "reach"
          - "reachctl*"

core:
  - changed-files:
      - any-glob-to-any-file:
          - "crates/**"
          - "src/core/**"
          - "src/determinism/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "**/*.md"
          - "apps/docs/**"

plugins:
  - changed-files:
      - any-glob-to-any-file:
          - "plugins/**"
          - "src/cli/plugins-cli.ts"

examples:
  - changed-files:
      - any-glob-to-any-file:
          - "examples/**"

presets:
  - changed-files:
      - any-glob-to-any-file:
          - "presets/**"
          - "policy-packs/**"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.test.ts"
          - "**/*.test.js"
          - "tests/**"
          - "src/**/__tests__/**"

rust:
  - changed-files:
      - any-glob-to-any-file:
          - "crates/**"
          - "**/*.rs"

go:
  - changed-files:
      - any-glob-to-any-file:
          - "services/**/*.go"
          - "tools/**/*.go"
          - "**/*.go"

typescript:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**/*.ts"
          - "scripts/**/*.ts"
          - "**/*.ts"
