name: Doctor Output Validation

on:
  push:
    branches: [main, master]
  pull_request:
    # Runs on every PR to ensure CLI output contract is maintained
    branches: ['**']
  workflow_dispatch:

jobs:
  validate-doctor:
    name: Validate Doctor Output
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.7'
          cache: true

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Validation Script
        # Executes the TypeScript validator which runs 'go run . --json'
        # and asserts all required probes (git, docker, cargo, etc.) are present.
        run: npx tsx tools/doctor/validate-cli.ts