import * as path from 'path';
import { evaluateDecisionFallback, validateOutcomesFallback, validateStructureFallback, validateProbabilitiesFallback, DecisionInput, DecisionOutput } from './fallback';

let wasmModule: any = null;

try {
  // Attempt to load the WASM module generated by wasm-pack
  // In a real build, this path is relative to dist/
  wasmModule = require('../pkg/decision_engine_rs');
} catch (e) {
  console.warn("WARN: Failed to load WASM decision engine. Falling back to TS implementation.", e);
}

/**
 * Evaluates a decision using Minimax Regret.
 * Uses Rust/WASM if available, falls back to TS.
 */
export function evaluateDecision(input: DecisionInput): DecisionOutput {
  if (wasmModule) {
    try {
      const inputJson = JSON.stringify(input);
      const outputJson = wasmModule.evaluate_decision(inputJson);
      return JSON.parse(outputJson);
    } catch (e) {
      console.error("ERROR: WASM execution failed. Using fallback.", e);
      return evaluateDecisionFallback(input);
    }
  }
  return evaluateDecisionFallback(input);
}

/**
 * Validates that the decision input outcomes are complete and finite.
 * Returns true if valid, throws an error if invalid.
 */
export function validateOutcomes(input: DecisionInput): boolean {
  if (wasmModule) {
    try {
      const inputJson = JSON.stringify(input);
      return wasmModule.validate_outcomes(inputJson);
    } catch (e) {
      console.error("ERROR: WASM validation failed.", e);
      return validateOutcomesFallback(input);
    }
  }
  return validateOutcomesFallback(input);
}

/**
 * Validates that the decision input structure is complete (no orphaned actions or states).
 * Does not check for finite values.
 */
export function validateStructure(input: DecisionInput): boolean {
  if (wasmModule) {
    try {
      const inputJson = JSON.stringify(input);
      return wasmModule.validate_structure(inputJson);
    } catch (e) {
      console.error("ERROR: WASM validation failed.", e);
      return validateStructureFallback(input);
    }
  }
  return validateStructureFallback(input);
}

/**
 * Validates that the decision input weights (probabilities) are between 0 and 1.
 */
export function validateProbabilities(input: DecisionInput): boolean {
  if (wasmModule) {
    try {
      const inputJson = JSON.stringify(input);
      return wasmModule.validate_probabilities(inputJson);
    } catch (e) {
      console.error("ERROR: WASM validation failed.", e);
      return validateProbabilitiesFallback(input);
    }
  }
  return validateProbabilitiesFallback(input);
}

// Re-export types
export { DecisionInput, DecisionOutput };

// Usage Example (for verification)
/*
const input = {
  actions: ["a1", "a2"],
  states: ["s1", "s2"],
  outcomes: { "a1": {"s1": 10, "s2": 5}, "a2": {"s1": 0, "s2": 20} }
};
console.log(evaluateDecision(input));
*/