name: Documentation Improvement
description: Suggest improvements to documentation
title: "[DOCS] "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve the documentation! Report typos, unclear sections, or missing info.

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What type of documentation?
      options:
        - README
        - API Reference
        - Examples
        - Tutorial/Guide
        - Architecture Docs
        - Contributing Guide
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: File path or URL
      placeholder: e.g., docs/cli.md or examples/README.md
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What's wrong or missing?
      placeholder: |
        The section about X is unclear because...
        OR
        There's a typo in paragraph 3...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should it be fixed or improved?
      placeholder: |
        It should say:
        ```
        reach run example --verbose
        ```
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR to fix this
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other details
