name: Feature request
description: Propose a new capability or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the user problem first, then the proposed solution.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user workflow is blocked or painful today?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the desired behavior and API/UX impact.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: scope
    attributes:
      label: Scope and impact
      description: Which components are affected (mobile, runner, engine, protocol)?
