openapi: 3.1.0
info:
  title: Reach Mobile API Contract
  version: 0.1.0
servers:
  - url: http://localhost:8080
paths:
  /v1/mobile/handshake/challenge:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HandshakeChallengeRequest'
      responses:
        '200':
          description: Challenge issued
          content:
            application/json:
              schema:
                type: object
                properties:
                  challenge: { type: string }
  /v1/mobile/handshake/complete:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HandshakeCompleteRequest'
      responses:
        '200':
          description: Session issued
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HandshakeSession'
  /v1/mobile/policy/preflight:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PolicyPreflightRequest'
      responses:
        '200':
          description: Decision
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyPreflightResponse'
  /v1/runs:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunPackRequest'
      responses:
        '201':
          description: Run created
  /v1/mobile/runs/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Redacted run timeline
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunTimelineResponse'
  /v1/mobile/share-tokens:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                run_id: { type: string }
              required: [run_id]
      responses:
        '201':
          description: Share token
  /v1/mobile/share/{token}:
    get:
      parameters:
        - in: path
          name: token
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Shared run redacted timeline
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunTimelineResponse'
components:
  schemas:
    HandshakeChallengeRequest:
      type: object
      properties:
        node_id: { type: string }
        org_id: { type: string }
        public_key: { type: string, description: base64-ed25519-public-key }
      required: [node_id, org_id, public_key]
    HandshakeCompleteRequest:
      type: object
      properties:
        challenge: { type: string }
        signature: { type: string, description: base64-ed25519-signature }
      required: [challenge, signature]
    HandshakeSession:
      type: object
      properties:
        session_token: { type: string }
        expires_in_seconds: { type: integer }
        node_id: { type: string }
        org_id: { type: string }
      required: [session_token, expires_in_seconds, node_id, org_id]
    PolicyPreflightRequest:
      type: object
      properties:
        capabilities:
          type: array
          items: { type: string }
      required: [capabilities]
    PolicyPreflightResponse:
      type: object
      properties:
        allowed: { type: boolean }
        required_gate: { type: boolean }
        missing_capabilities:
          type: array
          items: { type: string }
      required: [allowed, required_gate, missing_capabilities]
    RunPackRequest:
      type: object
      properties:
        capabilities:
          type: array
          items: { type: string }
        plan_tier: { type: string }
      required: [capabilities]
    TimelineEvent:
      type: object
      properties:
        id: { type: integer }
        type: { type: string }
        payload:
          type: object
          additionalProperties: true
        created_at: { type: string, format: date-time }
      required: [id, type, payload, created_at]
    RunTimelineResponse:
      type: object
      properties:
        run_id: { type: string }
        timeline:
          type: array
          items:
            $ref: '#/components/schemas/TimelineEvent'
      required: [run_id, timeline]
