/**
 * Example Renderer Plugin
 *
 * Demonstrates custom output formatting for Reach results.
 */

module.exports = {
  /**
   * Register renderers with Reach
   * @returns {Object} Renderers to register
   */
  register() {
    return {
      renderers: {
        /**
         * Compact JSON renderer (minified)
         */
        "json-compact": {
          description: "Minified JSON output",
          contentType: "application/json",

          render(data) {
            return JSON.stringify(data);
          },
        },

        /**
         * Pretty JSON renderer
         */
        "json-pretty": {
          description: "Formatted JSON with indentation",
          contentType: "application/json",

          render(data) {
            return JSON.stringify(data, null, 2);
          },
        },

        /**
         * Markdown table renderer
         */
        markdown: {
          description: "Markdown formatted output",
          contentType: "text/markdown",

          render(data) {
            const lines = ["# Reach Execution Result", ""];

            // Summary table
            lines.push("## Summary");
            lines.push("");
            lines.push("| Property | Value |");
            lines.push("|----------|-------|");

            if (data.id) {
              lines.push(`| ID | ${data.id} |`);
            }
            if (data.status) {
              lines.push(`| Status | ${data.status} |`);
            }
            if (data.timestamp) {
              lines.push(`| Timestamp | ${data.timestamp} |`);
            }
            if (data.fingerprint) {
              lines.push(`| Fingerprint | \`${data.fingerprint}\` |`);
            }

            lines.push("");

            // Outputs section
            if (data.outputs) {
              lines.push("## Outputs");
              lines.push("");
              lines.push("```json");
              lines.push(JSON.stringify(data.outputs, null, 2));
              lines.push("```");
              lines.push("");
            }

            // Evidence section
            if (data.evidence && data.evidence.length > 0) {
              lines.push("## Evidence");
              lines.push("");
              lines.push("| # | Source | Confidence |");
              lines.push("|---|--------|------------|");

              for (let i = 0; i < data.evidence.length; i++) {
                const ev = data.evidence[i];
                lines.push(`| ${i + 1} | ${ev.source} | ${ev.confidence || "N/A"} |`);
              }

              lines.push("");
            }

            // Footer
            lines.push("---");
            lines.push("*Generated by Reach with renderer-example plugin*");

            return lines.join("\\n");
          },
        },

        /**
         * HTML renderer
         */
        html: {
          description: "HTML formatted output",
          contentType: "text/html",

          render(data) {
            const escapeHtml = (str) => {
              return String(str)
                .replace(/&/g, "&amp;")
                .replace(/</g, "&lt;")
                .replace(/>/g, "&gt;")
                .replace(/"/g, "&quot;");
            };

            const parts = [
              "<!DOCTYPE html>",
              "<html>",
              "<head>",
              '  <meta charset="UTF-8">',
              "  <title>Reach Execution Result</title>",
              "  <style>",
              "    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 2em auto; padding: 0 1em; }",
              "    .header { border-bottom: 2px solid #333; padding-bottom: 1em; margin-bottom: 2em; }",
              "    .status-success { color: #28a745; }",
              "    .status-failure { color: #dc3545; }",
              "    pre { background: #f5f5f5; padding: 1em; border-radius: 4px; overflow-x: auto; }",
              "    table { border-collapse: collapse; width: 100%; }",
              "    th, td { border: 1px solid #ddd; padding: 0.5em; text-align: left; }",
              "    th { background: #f5f5f5; }",
              "  </style>",
              "</head>",
              "<body>",
              '  <div class="header">',
              "    <h1>🎯 Reach Execution Result</h1>",
            ];

            if (data.status) {
              const statusClass = data.status === "success" ? "status-success" : "status-failure";
              parts.push(
                `    <p>Status: <span class=\"${statusClass}\">${escapeHtml(data.status)}</span></p>`,
              );
            }

            if (data.id) {
              parts.push(`    <p>ID: <code>${escapeHtml(data.id)}</code></p>`);
            }

            if (data.fingerprint) {
              parts.push(`    <p>Fingerprint: <code>${escapeHtml(data.fingerprint)}</code></p>`);
            }

            parts.push("  </div>");

            if (data.outputs) {
              parts.push("  <h2>Outputs</h2>");
              parts.push("  <pre>" + escapeHtml(JSON.stringify(data.outputs, null, 2)) + "</pre>");
            }

            if (data.evidence && data.evidence.length > 0) {
              parts.push("  <h2>Evidence</h2>");
              parts.push("  <table>");
              parts.push("    <tr><th>Source</th><th>Confidence</th></tr>");

              for (const ev of data.evidence) {
                parts.push(
                  `    <tr><td>${escapeHtml(ev.source)}</td><td>${escapeHtml(ev.confidence || "N/A")}</td></tr>`,
                );
              }

              parts.push("  </table>");
            }

            parts.push("</body>");
            parts.push("</html>");

            return parts.join("\\n");
          },
        },
      },
    };
  },
};
