import * as path from 'path';
import { evaluateDecisionFallback, DecisionInput, DecisionOutput } from './lib/fallback';

let wasmModule: any = null;

try {
  // Attempt to load the WASM module generated by wasm-pack
  // In a real build, this path is relative to dist/
  wasmModule = require('../pkg/decision_engine_rs');
} catch (e) {
  console.warn("WARN: Failed to load WASM decision engine. Falling back to TS implementation.", e);
}

/**
 * Evaluates a decision using Minimax Regret.
 * Uses Rust/WASM if available, falls back to TS.
 */
export function evaluateDecision(input: DecisionInput): DecisionOutput {
  if (wasmModule) {
    try {
      const inputJson = JSON.stringify(input);
      const outputJson = wasmModule.evaluate_decision(inputJson);
      return JSON.parse(outputJson);
    } catch (e) {
      console.error("ERROR: WASM execution failed. Using fallback.", e);
      return evaluateDecisionFallback(input);
    }
  }
  return evaluateDecisionFallback(input);
}

// Re-export types
export { DecisionInput, DecisionOutput };

// Usage Example (for verification)
/*
const input = {
  actions: ["a1", "a2"],
  states: ["s1", "s2"],
  outcomes: { "a1": {"s1": 10, "s2": 5}, "a2": {"s1": 0, "s2": 20} }
};
console.log(evaluateDecision(input));
*/